/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.fci.ticketmachine.core;

import javax.swing.JOptionPane;
import br.mackenzie.fci.ticketmachine.*;
import br.mackenzie.fci.ticketmachine.exception.PapelMoedaInvalidaException;
import java.util.Iterator;

/**
 *
 * @author Bruno
 */
public class jfBilhete extends javax.swing.JFrame {

    TicketMachine tm = new TicketMachine(10);

    /**
     * Creates new form jfBilhete
     */
    public jfBilhete() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSaldoTotal = new javax.swing.JLabel();
        btnEmitir = new javax.swing.JButton();
        btnTroco = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        txtEmitir = new javax.swing.JTextField();
        txtInserir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Saldo Atual");

        lblSaldoTotal.setText("0");

        btnEmitir.setText("Emitir");
        btnEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmitirActionPerformed(evt);
            }
        });

        btnTroco.setText("Troco");
        btnTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocoActionPerformed(evt);
            }
        });

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        txtEmitir.setName("txtEmitir"); // NOI18N

        jLabel2.setText("Valor do Bilhete: 5 reais");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(lblSaldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEmitir)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnInserir)
                                    .addComponent(btnTroco))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmitir)
                    .addComponent(txtEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(txtInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTroco)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("lblSaldo");
        lblSaldoTotal.getAccessibleContext().setAccessibleName("lblSaldoTotal");
        btnEmitir.getAccessibleContext().setAccessibleName("btnEmitir");
        btnTroco.getAccessibleContext().setAccessibleName("btnTroco");
        txtEmitir.getAccessibleContext().setAccessibleName("txtEmitir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmitirActionPerformed
        int TotalBilhetes = Integer.parseInt(txtEmitir.getText()) * 5;
        if (TotalBilhetes > tm.getSaldo()) {
            JOptionPane.showMessageDialog(null, "Saldo insuficiente!");
        } else {
            JOptionPane.showMessageDialog(null, "Bilhete(s) " + TotalBilhetes/5 + " emitido(s) com sucesso!");
            tm.setSaldo(tm.getSaldo() - TotalBilhetes);
            lblSaldoTotal.setText(String.valueOf(tm.getSaldo()));
        }
    }//GEN-LAST:event_btnEmitirActionPerformed

    private void btnTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocoActionPerformed

        if (tm.getSaldo() == 0) {
            JOptionPane.showMessageDialog(null, "O saldo atual é 0!");
            return;
        }

        PapelMoeda pm;
        Troco t = new Troco(tm.getSaldo());
        Iterator<PapelMoeda> itTroco = t.getIterator();
        StringBuilder sb = new StringBuilder();
        sb.append("Efetuando o troco com:\n");
        while (itTroco.hasNext()) {
            pm = itTroco.next();
            if (pm.getQuantidade() > 0) {
                if (pm.isNota) {
                    sb.append(pm.getQuantidade() + " nota(s) de " + pm.getValor() + "\n");
                } else {
                    sb.append(pm.getQuantidade() + " moeda(s) de " + pm.getValor() + "\n");
                }
            }
        }
        JOptionPane.showMessageDialog(null, sb);
        tm = new TicketMachine(200);
        lblSaldoTotal.setText(String.valueOf(tm.getSaldo()));
    }//GEN-LAST:event_btnTrocoActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        try {
            tm.inserir(Double.parseDouble(txtInserir.getText().toString()));
            lblSaldoTotal.setText(String.valueOf(tm.getSaldo()));
        } catch (PapelMoedaInvalidaException e) {
            JOptionPane.showMessageDialog(null, "Nota/Moeda inválida, favor inserir outra!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Dados invalidos!");
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfBilhete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfBilhete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfBilhete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfBilhete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfBilhete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmitir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnTroco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblSaldoTotal;
    private javax.swing.JTextField txtEmitir;
    private javax.swing.JTextField txtInserir;
    // End of variables declaration//GEN-END:variables
}
